### PR TITLE
Added option for separate client IPs about proxy protocol use or not.

### PR DESCRIPTION
**Pull request by heat1024**
Will add option for separate client IPs about proxy protocol use or not.

So, can use both clients that use the proxy protocol(pre setted) and do not on one proftpd server at the same time.

- Config example
```Vim
<IfModule mod_proxy_protocol.c>
  ProxyProtocolEngine on
  ProxyProtocolTimeout 3sec

  # can add more parameter
  ProxyClientAddress 192.168.18.33/24 192.168.33.2 192.168.33.1/31
</IfModule>
```

### CODE REVIEW

**Comment by Castaglia** [comment]
Nice.  I may try to clean this up a little bit, but I like the idea!  I'm wondering if [classes](http://www.proftpd.org/docs/howto/Classes.html) might be more flexible/useful...

**Comment by Castaglia** [comment]
In theory, this should already be possible with this PR, using classes and the [`mod_ifsession`](http://www.proftpd.org/docs/contrib/mod_ifsession.html) module, _e.g._:
```
<Class expect-proxy-protocol>
  From 192.168.18.33/24
  From 192.168.33.2
  From 192.168.33.1/31
</Class>

<IfClass expect-proxy-protocol>
  <IfModule mod_proxy_protocol.c>
    ProxyProtocolEngine on
    ProxyProtocolTimeout 3sec
  </IfModule>
</IfClass>
```

I'll work on some integration tests to ensure that the above configuration works; it should.

**Comment by heat1024** [comment]
Wow, I didn't know about configuration what using mod_ifsession and Classes combination can available.

So I tried to add that function in mod_proxy_protocol.

Thanks for testing!

I want to know classes configure has working!

**Comment by Castaglia** [comment]
@heat1024 I added some regression tests (see https://github.com/Castaglia/proftpd-mod_proxy_protocol/commit/d872fa5489869674eb42e57b9f975572e0b1f713); the configuration I proposed, using [classes](http://www.proftpd.org/docs/howto/Classes.html), and the [`mod_ifsession`](http://www.proftpd.org/docs/contrib/mod_ifsession.html) module, works as you would want, for enabling PROXY support only for specific source IPs.

**Comment by Castaglia** [comment]
@heat1024 given the use of classes and `mod_ifsession`, would you mind if I close this PR?

**Comment by heat1024** [comment]
Oh, yes. I think you can close this PR.

Because you showed to me the mod_ifsession module works perfectly. 😄

**Pull request closed without merging**
